//
//  Auto-generated by NoZ Editor - DO NOT EDIT
//

namespace noz;

public static class EditorAssets
{
    public static class Names
    {
        public const string EditorPalette = "editor_palette";
    }

    public static class Textures
    {
        public static Texture? EditorPalette;
    }

    public static void LoadAssets()
    {
        Textures.EditorPalette = (Texture?)Asset.Load(AssetType.Texture, Names.EditorPalette);
    }

    public static void ReloadAssets()
    {
        // TODO: hot reload
    }

    public static void UnloadAssets()
    {
        Textures.EditorPalette?.Dispose();
    }
}
