//
//  NoZ - Copyright(c) 2026 NoZ Games, LLC
//

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NoZ.Generators;

[Generator]
public class StateMachineGenerator : IIncrementalGenerator
{
    private struct ClassInfo
    {
        public string Namespace;
        public string ClassName;
        public string EnumTypeName;
        public bool IsStatic;
        public ImmutableArray<string> EnterStates;
        public ImmutableArray<string> LeaveStates;
        public ImmutableArray<string> UpdateStates;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with [StateMachine] attribute
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "NoZ.StateMachineAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
                    var classSymbol = ctx.TargetSymbol as INamedTypeSymbol;
                    
                    // Extract the fully qualified namespace string
                    var className = classDecl.Identifier.ToString();
                    var namespaceName = classSymbol?.ContainingNamespace?.ToDisplayString() ?? "Global";
                    var isStatic = classDecl.Modifiers.Any(m => m.Text == "static");

                    var attribute = ctx.Attributes[0];

                    string enumType = "unknown";
                    var enterStates = ImmutableArray<string>.Empty;
                    var leaveStates = ImmutableArray<string>.Empty;
                    var updateStates = ImmutableArray<string>.Empty;

                    // 2. Extract the 'Type enumType' argument passed to the constructor
                    if (attribute.ConstructorArguments.Length > 0)
                    {
                        var argumentValue = attribute.ConstructorArguments[0].Value;
                        
                        // When an attribute takes a 'Type', the Roslyn value is typed as an ISymbol (specifically INamedTypeSymbol)
                        if (argumentValue is INamedTypeSymbol enumSymbol)
                        {
                            enumType = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                            var enumValues = enumSymbol.GetMembers()
                                .OfType<IFieldSymbol>()
                                .Where(field => field.HasConstantValue)
                                .Select(field => field.Name)
                                .ToImmutableArray();

                            enterStates = FindStateCallbacks(classSymbol, enumValues, "OnEnter");
                            leaveStates = FindStateCallbacks(classSymbol, enumValues, "OnLeave");
                            updateStates = FindStateCallbacks(classSymbol, enumValues, "OnUpdate");
                        }
                    }

                    return new ClassInfo
                    {
                        ClassName = className,
                        Namespace = namespaceName,
                        IsStatic = isStatic,
                        EnumTypeName = enumType,
                        EnterStates = enterStates,
                        LeaveStates = leaveStates,
                        UpdateStates = updateStates
                    };
                })
            .Collect();

        context.RegisterSourceOutput(classDeclarations, GenerateSource);
    }

    private static ImmutableArray<string> FindStateCallbacks(
        INamedTypeSymbol? classSymbol,
        ImmutableArray<string> enumValues,
        string prefix)
    {
        if (classSymbol == null)
            return ImmutableArray<string>.Empty;

        return enumValues
            .Where(state => classSymbol.GetMembers(prefix + state)
                .OfType<IMethodSymbol>()
                .Any(method => method.Parameters.Length == 0 &&
                               method.ReturnsVoid &&
                               !method.IsGenericMethod))
            .ToImmutableArray();
    }


    private static string GenerateClass(ClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace) && info.Namespace != "<global namespace>")
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var staticPrefix = info.IsStatic ? "static " : "";
        var methodAccess = info.IsStatic ? "private " : "protected ";

        // Open containing types
        var indent = "";
        sb.AppendLine($"{indent}{staticPrefix}partial class {info.ClassName}");
        sb.AppendLine($"{indent}{{");
        indent += "    ";

        sb.AppendLine($"{indent}public {staticPrefix}{info.EnumTypeName} State {{ get; private set; }}");
        sb.AppendLine();

        sb.AppendLine($"{indent}{methodAccess}{staticPrefix}void SetState({info.EnumTypeName} state)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (State.Equals(state)) return;");
        AppendCallbackSwitch(sb, indent + "    ", "State", info.EnumTypeName, "OnLeave", info.LeaveStates);
        sb.AppendLine($"{indent}    State = state;");
        AppendCallbackSwitch(sb, indent + "    ", "State", info.EnumTypeName, "OnEnter", info.EnterStates);
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        sb.AppendLine($"{indent}{methodAccess}{staticPrefix}void UpdateState()");
        sb.AppendLine($"{indent}{{");
        AppendCallbackSwitch(sb, indent + "    ", "State", info.EnumTypeName, "OnUpdate", info.UpdateStates);
        sb.AppendLine($"{indent}}}");


        // Close containing types
        indent = indent.Substring(4);
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private static void AppendCallbackSwitch(
        StringBuilder sb,
        string indent,
        string stateExpression,
        string enumTypeName,
        string callbackPrefix,
        ImmutableArray<string> states)
    {
        if (states.IsDefaultOrEmpty)
            return;

        sb.AppendLine($"{indent}switch ({stateExpression})");
        sb.AppendLine($"{indent}{{");
        foreach (var state in states)
        {
            sb.AppendLine($"{indent}    case {enumTypeName}.{state}:");
            sb.AppendLine($"{indent}        {callbackPrefix}{state}();");
            sb.AppendLine($"{indent}        break;");
        }
        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateSource(
        SourceProductionContext context,
        ImmutableArray<ClassInfo> classes)
    {
        foreach (var classInfo in classes)
            context.AddSource($"{classInfo.ClassName}.g.cs", GenerateClass(classInfo));
    }
}
